# Generated by Django 5.1.7 on 2025-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
