# Generated by Django 5.1.7 on 2025-03-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reserva_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('targeta', 'Tarjeta')], default='efectivo', max_length=10),
        ),
    ]
