# Generated by Django 5.1.7 on 2025-03-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0013_masaje_descriptionsh'),
        ('usuarios', '0004_reserva_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idMasaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masajes.masaje'),
        ),
    ]
