# Generated by Django 5.1.7 on 2025-03-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
