# Generated by Django 5.1.7 on 2025-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='delete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
