# Generated by Django 5.1.7 on 2025-04-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_worker_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.DurationField(default=models.F('idMasaje__duracion')),
        ),
        migrations.CreateModel(
            name='Fiestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('general', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.worker')),
            ],
        ),
    ]
