# Generated by Django 5.1.7 on 2025-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_reserva_duracion_fiestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotosPerfil/'),
        ),
    ]
