# Generated by Django 5.1.7 on 2025-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='delete_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
