# Generated by Django 5.1.7 on 2025-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_worker_delete_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
