# Generated by Django 5.1.7 on 2025-05-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_reserva_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recover_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
