# Generated by Django 5.1.7 on 2025-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masaje',
            name='tipo',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
