# Generated by Django 5.1.7 on 2025-03-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0002_masaje_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='masaje',
            old_name='nom',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='masaje',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masajes.tipomasaje'),
        ),
    ]
