# Generated by Django 5.1.7 on 2025-03-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0003_tipomasaje_rename_nom_masaje_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masaje',
            name='tipo',
        ),
    ]
