# Generated by Django 5.1.7 on 2025-03-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0004_remove_masaje_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='masaje',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masajes.tipomasaje'),
        ),
    ]
