# Generated by Django 5.1.7 on 2025-03-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0005_masaje_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masaje',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masajes.tipomasaje'),
        ),
    ]
