# Generated by Django 5.1.7 on 2025-03-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0006_alter_masaje_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masaje',
            name='tipo',
        ),
    ]
