# Generated by Django 5.1.7 on 2025-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0008_masaje_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomasaje',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='masaje',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='masaje',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='masajes/static/'),
        ),
    ]
