# Generated by Django 5.1.7 on 2025-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0009_tipomasaje_description_alter_masaje_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomasaje',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='masajes/static/'),
        ),
    ]
