# Generated by Django 5.1.7 on 2025-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0010_tipomasaje_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masaje',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='masajes/static/'),
        ),
        migrations.AlterField(
            model_name='tipomasaje',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='masajes/static/'),
        ),
    ]
