# Generated by Django 5.1.7 on 2025-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0011_alter_masaje_foto_alter_tipomasaje_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masaje',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
