# Generated by Django 5.1.7 on 2025-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0012_alter_masaje_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='masaje',
            name='descriptionSh',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
