# Generated by Django 5.1.7 on 2025-04-08 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masajes', '0013_masaje_descriptionsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='masaje',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(hours=1)),
        ),
    ]
